FROM python:3.8-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG CONSUMER_KEY
ENV CONSUMER_KEY=$CONSUMER_KEY

ARG CONSUMER_SECRET
ENV CONSUMER_SECRET=$CONSUMER_SECRET

ARG ACCESS_TOKEN
ENV ACCESS_TOKEN=$ACCESS_TOKEN

ARG ACCESS_TOKEN_SECRET
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET

ARG FIRST_USER
ENV FIRST_USER=$FIRST_USER

ARG SECOND_USER
ENV SECOND_USER=$SECOND_USER

ARG MONGO_USER
ENV MONGO_USER=$MONGO_USER

ARG MONGO_PASSWORD
ENV MONGO_PASSWORD=$MONGO_PASSWORD

CMD ['python', 'analyzeOverlaps.py']